version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
  - 300000000MYCEL
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
  - 100000MYCEL
validators:
- name: alice
  bonded: 100000000stake
